version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
#    platform: linux/amd64
    container_name: ollama
    ports:
      - '11434:11434'
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 16G
#    volumes:
#      - './ollama:/root/.ollama'