version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    privileged: true
    ports:
      - '11434:11434'
    volumes:
      - './ollama:/root/.ollama'
      - '/dev/dri:/dev/dri'
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          cpus: '14'
          memory: 16G